<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // Insertar datos en la tabla `user`
        DB::table('user')->insert([
            'first_name' => 'Javier Andres',
            'last_name' => 'Rojas Erazo',
            'document_number' => '1144192322',
            'password' => Hash::make('0000'), // Se recomienda usar un hash para la contraseña
            'email' => 'jare_123@hotmail.es',
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Insertar datos en la tabla `departament`
        DB::table('departament')->insert([
            ['id' => 1, 'name' => 'Informatica', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'Desarrollo', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'Administracion', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'Logistica', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'Contabilidad', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'Recursos Humanos', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Insertar datos en la tabla `country`
        DB::table('country')->insert([
            ['id' => 1, 'name' => 'Argentina', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'Brasil', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'Colombia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'México', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'España', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'Francia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'name' => 'Italia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'name' => 'Australia', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'name' => 'Canadá', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'name' => 'Japón', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Insertar datos en la tabla `city`
        DB::table('city')->insert([
            ['id' => 1, 'name' => 'Buenos Aires', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'Córdoba', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'Rosario', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'Mendoza', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'La Plata', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 6, 'name' => 'Salta', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 7, 'name' => 'Santa Fe', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 8, 'name' => 'Mar del Plata', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 9, 'name' => 'San Juan', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 10, 'name' => 'Neuquén', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 11, 'name' => 'Tucumán', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 12, 'name' => 'San Miguel de Tucumán', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 13, 'name' => 'Bahía Blanca', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 14, 'name' => 'La Rioja', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 15, 'name' => 'Corrientes', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 16, 'name' => 'Posadas', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 17, 'name' => 'Jujuy', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 18, 'name' => 'Formosa', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 19, 'name' => 'San Luis', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 20, 'name' => 'Rawson', 'country_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 21, 'name' => 'Río de Janeiro', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 22, 'name' => 'São Paulo', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 23, 'name' => 'Brasilia', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 24, 'name' => 'Salvador', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 25, 'name' => 'Fortaleza', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 26, 'name' => 'Belo Horizonte', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 27, 'name' => 'Manaos', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 28, 'name' => 'Curitiba', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 29, 'name' => 'Recife', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 30, 'name' => 'Porto Alegre', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 31, 'name' => 'Belém', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 32, 'name' => 'Goiânia', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 33, 'name' => 'Campinas', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 34, 'name' => 'São Luís', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 35, 'name' => 'Guarulhos', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 36, 'name' => 'São Gonçalo', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 37, 'name' => 'Maceió', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 38, 'name' => 'Campo Grande', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 39, 'name' => 'Natal', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 40, 'name' => 'Teresina', 'country_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 41, 'name' => 'Bogotá', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 42, 'name' => 'Medellín', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 43, 'name' => 'Cali', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 44, 'name' => 'Barranquilla', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 45, 'name' => 'Cartagena', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 46, 'name' => 'Cúcuta', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 47, 'name' => 'Soledad', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 48, 'name' => 'Ibagué', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 49, 'name' => 'Bucaramanga', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 50, 'name' => 'Santa Marta', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 51, 'name' => 'Villavicencio', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 52, 'name' => 'Pasto', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 53, 'name' => 'Manizales', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 54, 'name' => 'Neiva', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 55, 'name' => 'Pereira', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 56, 'name' => 'Montería', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 57, 'name' => 'Popayán', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 58, 'name' => 'Valledupar', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 59, 'name' => 'Quibdó', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 60, 'name' => 'Armenia', 'country_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 61, 'name' => 'Ciudad de México', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 62, 'name' => 'Guadalajara', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 63, 'name' => 'Monterrey', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 64, 'name' => 'Puebla', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 65, 'name' => 'Tijuana', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 66, 'name' => 'León', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 67, 'name' => 'Juárez', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 68, 'name' => 'Zapopan', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 69, 'name' => 'Mérida', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 70, 'name' => 'Mexicali', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 71, 'name' => 'Acapulco', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 72, 'name' => 'Toluca', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 73, 'name' => 'Cancún', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 74, 'name' => 'Querétaro', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 75, 'name' => 'Morelia', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 76, 'name' => 'Culiacán', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 77, 'name' => 'Hermosillo', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 78, 'name' => 'Chihuahua', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 79, 'name' => 'Durango', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 80, 'name' => 'Saltillo', 'country_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 81, 'name' => 'Madrid', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 82, 'name' => 'Barcelona', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 83, 'name' => 'Valencia', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 84, 'name' => 'Sevilla', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 85, 'name' => 'Zaragoza', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 86, 'name' => 'Málaga', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 87, 'name' => 'Murcia', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 88, 'name' => 'Palma de Mallorca', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 89, 'name' => 'Bilbao', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 90, 'name' => 'Alicante', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 91, 'name' => 'Córdoba', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 92, 'name' => 'Valladolid', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 93, 'name' => 'Almería', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 94, 'name' => 'León', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 95, 'name' => 'Soria', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 96, 'name' => 'Oviedo', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 97, 'name' => 'La Coruña', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 98, 'name' => 'Gijón', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 99, 'name' => 'Logroño', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 100, 'name' => 'Pamplona', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 101, 'name' => 'La Rioja', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 102, 'name' => 'A Coruña', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 103, 'name' => 'Toledo', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 104, 'name' => 'Segovia', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 105, 'name' => 'Badajoz', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 106, 'name' => 'Jaén', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 107, 'name' => 'Ávila', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 108, 'name' => 'Ciudad Real', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 109, 'name' => 'Cáceres', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 110, 'name' => 'Huelva', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 111, 'name' => 'Albacete', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 112, 'name' => 'Ceuta', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 113, 'name' => 'Melilla', 'country_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 114, 'name' => 'Paris', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 115, 'name' => 'Marseille', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 116, 'name' => 'Lyon', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 117, 'name' => 'Toulouse', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 118, 'name' => 'Nice', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 119, 'name' => 'Nantes', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 120, 'name' => 'Strasbourg', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 121, 'name' => 'Montpellier', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 122, 'name' => 'Bordeaux', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 123, 'name' => 'Lille', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 124, 'name' => 'Rennes', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 125, 'name' => 'Le Havre', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 126, 'name' => 'Reims', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 127, 'name' => 'Le Mans', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 128, 'name' => 'Amiens', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 129, 'name' => 'Clermont-Ferrand', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 130, 'name' => 'Saint-Étienne', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 131, 'name' => 'Le Creusot', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 132, 'name' => 'Chalon-sur-Saône', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 133, 'name' => 'Auxerre', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 134, 'name' => 'Pau', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 135, 'name' => 'Dijon', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 136, 'name' => 'Grenoble', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 137, 'name' => 'Chambéry', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 138, 'name' => 'Moulins', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 139, 'name' => 'Nevers', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 140, 'name' => 'Aix-en-Provence', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 141, 'name' => 'Épinal', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 142, 'name' => 'Béziers', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 143, 'name' => 'La Roche-sur-Yon', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 144, 'name' => 'Quimper', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 145, 'name' => 'Vichy', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 146, 'name' => 'Colmar', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 147, 'name' => 'Saint-Malo', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 148, 'name' => 'Perpignan', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 149, 'name' => 'Cavaillon', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 150, 'name' => 'Rodez', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 151, 'name' => 'Saint-Quentin', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 152, 'name' => 'Thionville', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 153, 'name' => 'Sète', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 154, 'name' => 'Dole', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 155, 'name' => 'Dunkerque', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 156, 'name' => 'Belfort', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 157, 'name' => 'Tarbes', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 158, 'name' => 'Niort', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 159, 'name' => 'Châteauroux', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 160, 'name' => 'Chalon-sur-Saône', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 161, 'name' => 'Échirolles', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 162, 'name' => 'Montargis', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 163, 'name' => 'Échirolles', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 164, 'name' => 'La Rochelle', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 165, 'name' => 'Moulins', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 166, 'name' => 'Saint-Nazaire', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 167, 'name' => 'Thonon-les-Bains', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 168, 'name' => 'Epernay', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 169, 'name' => 'Aix-en-Provence', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 170, 'name' => 'Aubagne', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 171, 'name' => 'Arles', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 172, 'name' => 'Bagnères-de-Bigorre', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 173, 'name' => 'Chambéry', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 174, 'name' => 'Dijon', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 175, 'name' => 'Épinal', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 176, 'name' => 'Saint-Denis', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 177, 'name' => 'Périgueux', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 178, 'name' => 'Bourg-en-Bresse', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 179, 'name' => 'Auxerre', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 180, 'name' => 'Dijon', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 181, 'name' => 'Chalon-sur-Saône', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 182, 'name' => 'Vichy', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 183, 'name' => 'Châteauroux', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 184, 'name' => 'Nevers', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 185, 'name' => 'Moulins', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 186, 'name' => 'Vienne', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 187, 'name' => 'Cahors', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 188, 'name' => 'Bourges', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 189, 'name' => 'Saint-Omer', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 190, 'name' => 'Nevers', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 191, 'name' => 'Limoges', 'country_id' => 6, 'created_at' => now(), 'updated_at' => now()]
        ]);

        }

    }